<?php

/**
 * Game Specific Constants
 */

const BASE_GAME = 'BASE_GAME';
const EXP_EUROPEAN = 'EXP_EUROPEAN';

const BREED_GUNDOG      = 'gundog';
const BREED_HOUND       = 'hound';
const BREED_PASTORAL    = 'pastoral';
const BREED_TERRIER     = 'terrier';
const BREED_TOY         = 'toy';
const BREED_UTILITY     = 'utility';
const BREED_WORKING     = 'working';

const RESOURCE_STICK = 'stick';
const RESOURCE_BALL = 'ball';
const RESOURCE_TREAT = 'treat';
const RESOURCE_TOY = 'toy';

const WALKED = 'walked';
const BLOCK = 'block';
const REPUTATION = 'reputation';
const SWAP = 'swap';
const SCOUT = 'scout';

const LOCATION_BONUS_PLENTIFUL = 'plentiful';
const LOCATION_BONUS_REROUTED = 'rerouted';

const OBJECTIVE_EXPERIENCED = 'experienced';
const OBJECTIVE_STANDARD = 'standard';
const OBJECTIVE_SOLO = 'solo';

// PHASES
const PHASE_SET_UP = 'PHASE_SET_UP';
const PHASE_RECRUITMENT_1 = 'PHASE_RECRUITMENT_1';
const PHASE_RECRUITMENT_2 = 'PHASE_RECRUITMENT_2';
const PHASE_SELECTION = 'PHASE_SELECTION';
const PHASE_WALKING = 'PHASE_WALKING';
const PHASE_HOME_TIME = 'PHASE_HOME_TIME';

/**
 * Options
 */

const EXPANSION_EUROPEAN_DOGS_OPTION_ID = 101;
const EXPANSION_EUROPEAN_DOGS_OPTION_EXCLUDED = 0;
const EXPANSION_EUROPEAN_DOGS_OPTION_INCLUDED = 1;

const VARIANT_PACKED_PARK_OPTION_ID = 110;
const VARIANT_PACKED_PARK_OPTION = 'variant_packed_park';
const VARIANT_PACKED_PARK_OPTION_EXCLUDED = 0;
const VARIANT_PACKED_PARK_OPTION_INCLUDED = 1;

const VARIANT_GENTLE_WALK_OPTION_ID = 111;
const VARIANT_GENTLE_WALK_OPTION = 'variant_gentle_walk';
const VARIANT_GENTLE_WALK_OPTION_EXCLUDED = 0;
const VARIANT_GENTLE_WALK_OPTION_INCLUDED = 1;

const VARIANT_PREDICTABLE_FORECAST_OPTION_ID = 112;
const VARIANT_PREDICTABLE_FORECAST_OPTION = 'variant_predictable_forecast';
const VARIANT_PREDICTABLE_FORECAST_OPTION_EXCLUDED = 0;
const VARIANT_PREDICTABLE_FORECAST_OPTION_INCLUDED = 1;


/**
 * State
 */
const ST_GAME_SETUP = 1;

const ST_CHOOSE_OBJECTIVES = 5;
const ST_CHOOSE_OBJECTIVES_END = 6;

const ST_RECRUITMENT_START = 10;
const ST_RECRUITMENT_OFFER = 11;
const ST_RECRUITMENT_OFFER_NEXT = 12;
const ST_RECRUITMENT_RESOLVE_OFFERS = 15;
const ST_RECRUITMENT_TAKE_DOG = 16;
const ST_RECRUITMENT_TAKE_DOG_NEXT = 17;
const ST_RECRUITMENT_END = 20;

const ST_SELECTION_START = 30;
const ST_SELECTION_ACTIONS = 31;
const ST_SELECTION_PLACE_DOG_ON_LEAD = 32;
const ST_SELECTION_PLACE_DOG_ON_LEAD_SELECT_RESOURCES = 33;
const ST_SELECTION_PLACE_DOG_ON_LEAD_AFTER = 35;
const ST_SELECTION_END = 40;

const ST_WALKING_START = 50;
const ST_WALKING_MOVE_WALKER = 51;
const ST_WALKING_MOVE_WALKER_AFTER = 55;
const ST_WALKING_NEXT = 60;

const ST_HOME_TIME = 70;

const ST_ACTION_SWAP = 80;
const ST_ACTION_SCOUT_START = 81;
const ST_ACTION_SCOUT = 82;
const ST_ACTION_MOVE_AUTO_WALKER = 83;
const ST_ACTION_CRAFTY = 84;
const ST_ACTION_GAIN_RESOURCES_PRIVATE = 85;
const ST_ACTION_GAIN_RESOURCES = 86;

const ST_FINAL_SCORING = 95;
const ST_CATCH_STATE = 96;
const ST_GAME_END = 99;

/**
 * Actions
 */
const ACT_CHOOSE_OBJECTIVE = 'chooseObjective';
const ACT_CHANGE_OBJECTIVE = 'chooseObjective';
const ACT_PLACE_OFFER_ON_DOG = 'placeOfferOnDog';
const ACT_SKIP_PLACE_OFFER_ON_DOG = 'skipPlaceOfferOnDog';
const ACT_RECRUIT_DOG = 'recruitDog';
const ACT_PLACE_DOG_ON_LEAD = 'placeDogOnLead';
const ACT_PLACE_DOG_ON_LEAD_CANCEL = 'placeDogOnLeadCancel';
const ACT_PLACE_DOG_ON_LEAD_PAY_RESOURCES = 'placeDogOnLeadPayResources';
const ACT_CONFIRM_SELECTION = 'confirmSelection';
const ACT_CHANGE_SELECTION = 'changeSelection';
const ACT_MOVE_WALKER = 'moveWalker';
const ACT_ADDITIONAL_ACTION = 'additionalAction';
const ACT_CONFIRM_WALKING = 'confirmWalking';
const ACT_UNDO = 'undo';

const ACT_SWAP = 'swap';
const ACT_SCOUT_REPLACE = 'scoutReplace';
const ACT_SCOUT_END = 'scoutEnd';
const ACT_MOVE_AUTO_WALKER = 'moveAutoWalker';
const ACT_CANCEL = 'cancel';

const ACT_CRAFTY_CONFIRM = 'craftyConfirm';

const ACT_GAIN_RESOURCES_CONFIRM = 'gainResourcesConfirm';

/**
 * Locations
 */
const LOCATION_DECK = 'deck';
const LOCATION_FIELD = 'field';
const LOCATION_FIELD_1 = 'field_1';
const LOCATION_FIELD_2 = 'field_2';
const LOCATION_FIELD_3 = 'field_3';
const LOCATION_FIELD_4 = 'field_4';
const LOCATION_FIELD_5 = 'field_5';

const LOCATION_DISCARD = 'discard';
const LOCATION_PLAYER = 'player';
const LOCATION_LEAD = 'lead';

const LOCATION_PARK = 'park';

const LOCATION_SELECTED = 'selected';

const LOCATION_BREED_EXPERT_AWARDS = 'breed_expert';
const LOCATION_FORECAST = 'forecast';

/**
 * Global variables
 */
const CURRENT_ROUND = 'CURRENT_ROUND';
const CURRENT_PHASE = 'CURRENT_PHASE';
const OFFER_VALUE_REVEALED = 'OFFER_VALUE_REVEALED';
const OBJECTIVES_REVEALED = 'OBJECTIVES_REVEALED';

const SELECTION_DOG_ID_ = 'SELECTION_DOG_ID_';
const OBJECTIVE_ID_ = 'OBJECTIVE_ID_';

const ADDITIONAL_ACTIONS_ = 'ADDITIONAL_ACTIONS_';

const SCOUTED_CARDS = 'SCOUTED_CARDS';

const STATE_AFTER_SWAP = 'STATE_AFTER_SWAP';
const STATE_AFTER_SCOUT = 'STATE_AFTER_SCOUT';
const STATE_AFTER_GAIN_RESOURCES = 'STATE_AFTER_GAIN_RESOURCES';
const CURRENT_ACTION_ID = 'SWAP_ACTION_ID';

const LAST_WALKED_WALKER_ID = 'LAST_WALKED_WALKER_ID';
const MOVE_AUTO_WALKER_STEPS = 'MOVE_AUTO_WALKER_STEPS';
const MOVE_AUTO_WALKER_LOCATIONS = 'MOVE_AUTO_WALKER_LOCATIONS';

const USED_WALK_ABILITIES = 'USED_WALK_ABILITIES';

const GAIN_RESOURCES_NR_OF_RESOURCES = 'GAIN_RESOURCES_NR_OF_RESOURCES';
const GAIN_RESOURCES_REPUTATION = 'GAIN_RESOURCES_REPUTATION';
const GAIN_RESOURCES_RESOURCE_OPTIONS = 'GAIN_RESOURCES_RESOURCE_OPTIONS';

const FINAL_SCORING_BREAKDOWN = 'FINAL_SCORING_BREAKDOWN';

const FREE_DOG_ON_LEAD = 'FREE_DOG_ON_LEAD';

const GAIN_RESOURCES_PLAYER_IDS = 'GAIN_RESOURCES_PLAYER_IDS';

const WALKER_LAST_DIE_ROLL_ = 'WALKER_LAST_DIE_ROLL_';

/**
 * Additional Actions
 */
const WALKING_PAY_REPUTATION_ACCEPT = 'WALKING_PAY_REPUTATION_ACCEPT';
const WALKING_PAY_REPUTATION_DENY = 'WALKING_PAY_REPUTATION_DENY';
const WALKING_GAIN_LOCATION_BONUS = 'WALKING_GAIN_LOCATION_BONUS';
const WALKING_GAIN_LEAVING_THE_PARK_BONUS = 'WALKING_GAIN_LEAVING_THE_PARK_BONUS';

const USE_DOG_ABILITY = 'USE_DOG_ABILITY';
const USE_FORECAST_ABILITY = 'USE_FORECAST_ABILITY';

/**
 * DOG ABILITIES
 */
const EAGER = 'eager';
const CRAFTY = 'crafty';
const GO_FETCH = 'gofetch';
const OBEDIENT = 'obedient';
const PLAYMATE = 'playmate';
const SOCIAL_BUTTERFLY = 'socialbutterfly';
const SEARCH_AND_RESCUE = 'searchandrescue';
const PACK_DOG = 'packdog';
const RARING_TO_GO = 'raringtogo';
const SOCIABLE = 'sociable';
const BALL_HOG = 'ballhog';
const STICK_CHASER = 'stickchaser';
const TOY_COLLECTOR = 'toycollector';
const TREAT_LOVER = 'treatlover';
// EUROPEAN DOGS
const LONE_WOLF = 'lonewolf';
const WELL_TRAINED = 'welltrained';

const SELECTION_ABILITIES = [EAGER, CRAFTY];
const WALKING_ABILITIES = [GO_FETCH];

/**
 * Stats
 */
const PLAYER_PARK_BOARD_REPUTATION_ID = 50;
const PLAYER_PARK_BOARD_REPUTATION = 'PLAYER_PARK_BOARD_REPUTATION';
const PLAYER_DOGS_FINAL_SCORING_REPUTATION_ID = 51;
const PLAYER_DOGS_FINAL_SCORING_REPUTATION = 'PLAYER_DOGS_FINAL_SCORING_REPUTATION';
const PLAYER_BREED_EXPERT_WON_ID = 52;
const PLAYER_BREED_EXPERT_WON = 'PLAYER_BREED_EXPERT_WON';
const PLAYER_BREED_EXPERT_REPUTATION_ID = 53;
const PLAYER_BREED_EXPERT_REPUTATION = 'PLAYER_BREED_EXPERT_REPUTATION';
const PLAYER_OBJECTIVE_CARD_REPUTATION_ID = 54;
const PLAYER_OBJECTIVE_CARD_REPUTATION = 'PLAYER_OBJECTIVE_CARD_REPUTATION';
const PLAYER_REMAINING_RESOURCES_REPUTATION_ID = 55;
const PLAYER_REMAINING_RESOURCES_REPUTATION = 'PLAYER_REMAINING_RESOURCES_REPUTATION';
